### ISSUE TITLE
mod_magick and filters not applied after mod_wsgi app returns from request

### ISSUE THREAD

**Issue by bpluly** [minfrin/mod_magick#1]
This may well have nothing to do with mod_magick et al.
I have the following two blocks of config.

```
   <FilesMatch ".+\.(tiff|tif)$">
      <If "%{QUERY_STRING} =~ /./">
        Header set ImageFilter "Magick FORMAT"
        SetOutputFilter MAGICK;MAGICK_FORMAT
        MagickFormat PNG
      </If>
    </FilesMatch>
    
    <FilesMatch ".+\.(gif|jpe?g|png)$">
      SetOutputFilter MAGICK;MAGICK_RESIZE
      Header set ImageFilter "Magick RESIZE"      
      MagickResizeColumns 100 %{QUERY_STRING}
      <If "%{req:Width} != ''">
        MagickResizeColumns %{req:Width}
      </If>
    </FilesMatch>    

```
In a vanilla site config, with SSL but without WSGIDAEMON etc, this works as advertised. The VARY header is set, the ImageFilter is set and any .tiff is converted. The config is all within the Directory Block aliased on DocumentRoot (/var/www/html)

With the WSGIDAEMON regardless whether it's in a Directory Block or just in the VirtualHost the config is not executed.

As I say this may well have nothing to do with the WSGI and the app but I thought that WSGI passed on the response to the regular chain. That said the only logging I get is if the app breaks. That hasn't concerned me so far I do my own access logging but it may mean the Response is avoiding the regular chain.

If I figure it out in the meantime I'll update.

Otherwise, it's all good.

Ta

S

**Comment by minfrin** [comment]
Using `<Directory>` (and `<Files>`) only covers files served off disk, if they're dynamic they need to be in a `<Location>`.

I suspect what's happening is that the config doesn't apply (to a non directory), the filter(s) isn't inserted, and nothing happens.

Looks like we need a debug level message to confirm the MAGICK filter has been inserted, so there isn't a wall of silence.

**Comment by minfrin** [comment]
Try this to add a debug message:

https://github.com/minfrin/mod_magick/pull/2

**Comment by bpluly** [comment]
I added the header ImageFilter to do a similar thing.

**Comment by bpluly** [comment]
Building with the debug logline confirms that if the <LocationMatch> is true then mod_magick is called. So as suspected it;s nothing to do with mod_magick. 

Just a note, to build (on AWS Linux 2) I needed to autoreconf for a working ./configure
